<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUMD1zZp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUMD1zZp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUMD1zZp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUMD1zZp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUMD1zZp\App_KernelDevDebugContainer([
    'container.build_hash' => 'UMD1zZp',
    'container.build_id' => '1358988a',
    'container.build_time' => 1609749140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUMD1zZp');
